config/routes.rb
Rails.application.routes.draw do
  root :to => 'contacts#index'

  resources :contacts do
    resources :phones, :only => [:new, :create]
  end

  resources :phones, :except => [:new, :create]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :phones
	validates :name, presence: true
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  validates :number, :presence => true
  validates :contact_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = Contact.all
	end

	def create
		@contact = Contact.new(params[:contact])
		if @contact.save
			@phone = Phone.new(:number => @contact.phone,
											:contact_id => @contact.id)
			@phone.save
			flash[:notice] = "Your contact was saved to Wikipages."
			redirect_to contact_path(@contact)
		else
			render 'new'
		end
	end

	def new
		@contact = Contact.new
	end

	def show
		@contact = Contact.find(params[:id])
		render('contacts/show.html.erb')
	end

	def edit
		@contact = Contact.find(params[:id])
	end

	def update
		@contact = Contact.find(params[:id])
		if @contact.update(params[:contact])
			redirect_to contact_path(@contact)
		else
			render 'edit'
		end
	end

	def destroy
		@contact = Contact.find(params[:id])
		@contact.destroy
		redirect_to contacts_path
	end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
	def new
		contact = Contact.find(params[:contact_id])
		@phone = contact.phones.new
		render('phones/new.html.erb')
	end

	def create
		@phone = Phone.new(:number => params[:number],
											:contact_id => params[:contact_id])
		@contact = Contact.find(params[:contact_id])
		if @phone.save
			render('phones/success.html.erb')
		else
			render('phones/new.html.erb')
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<label for="contact_name">Name</label>
<input id="contact_name" name="contact[name]" type="text" value="<%= @contact.name %>">
<label for="contact_phone">Phone</label>
<input id="contact_phone" name="contact[phone]" type="text" value="<%= @contact.phone %>">
<label for="contact_email">Email</label>
<input id="contact_email" name="contact[email]" type="text" value="<%= @contact.email %>">

app/views/contacts/destroy.html.erb
<h1>Contact deleted</h1>

<p>Would you like to <a href="/contacts/">see all contacts</a> or <a href="/contacts/new">create a new contact</a>?</p>

app/views/contacts/edit.html.erb
<% content_for(:title, "Edit contact | Wikipages") %>

<h1>Edit contact</h1>

<%= render('layouts/errors', :object => @contact) %>

<form action="/contacts/<%= @contact.id %>" method="post">
  <input name="_method" type="hidden" value="patch">
  <%= render('form') %>
  <button>Update Contact</button>
</form>

app/views/contacts/index.html.erb
<% content_for(:title, "Contacts | Wikipages") %>

<h1 class="page-header">Contacts</h1>

<ul>
	<% @contacts.each do |contact| %>
		<li><a href='/contacts/<%= contact.id %>'><%= contact.name %></a></li>
	<% end %>
</ul>

<%= link_to "New contact", new_contact_path, :class => "btn btn-default" %>

app/views/contacts/new.html.erb
<% content_for(:title, "New contact | Wikipages") %>

<h1>New contact</h1>

<%= render('layouts/errors', :object => @contact) %>

<form action="/contacts" method="post">
  <%= render('form') %>
  <button>Create Contact</button>
</form>

app/views/contacts/show.html.erb
<% content_for(:title, "Your contact | Wikipages") %>

<h1><%= @contact.name %></h1>

<p>Phones:</p>
<ul>
  <% @contact.phones.each do |phone| %>
    <li>
      <%= phone.number %> |
      <a href="/contacts/<%= @contact.id %>/phones/<%= phone.id %>/edit">Edit</a> |
      <a href="/contacts/<%= @contact.id %>/phones/<%= phone.id %>"
         data-confirm="You sure?"
         data-method="delete"
         rel="nofollow">Delete</a>
    </li>
  <% end %>
</ul>

<p>Email: <%= @contact.email %></p>

<p><a href="/contacts/<%= @contact.id %>/phones/new">Add phone</a></p>

<p><a href="/contacts/<%= @contact.id %>/edit">Edit this contact</a>
<a href="/contacts/<%= @contact.id %>"
		data-confirm="Are you sure?"
		data-method="delete"
		rel="nofollow">Delete this contact</a></p>
<p><a href="/contacts/">Return to contacts listing</a></p>

app/views/contacts/success.html.erb
<h1>Contact saved!</h1>

<p>Your contact was successfully saved.</p>

<p><a href="/contacts/<%= @contact.id %>">View <%= @contact.name %></a></p>

<p><a href="/contacts">Return to contact listing</a></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</div>
</body>
</html>

app/views/phones/new.html.erb
<% content_for(:title, "New phone number | Wikipages") %>

<h1>New phone number for <%= @phone.contact.name %></h1>

<%= render('layouts/errors', :object => @phone) %>

<form action="/contacts/<%= @phone.contact.id %>/phones" method="post">
  <label for="phone_number">Number</label>
  <input id="phone_number" name="number" type="text" value="<%= @phone.number %>">
  <button>Add phone</button>
</form>

app/views/phones/success.html.erb
<h1>Phone number saved!</h1>

<p>Your phone number was successfully saved.</p>

<p><a href="/contacts/<%= @contact.id %>">View <%= @contact.name %></a></p>

<p><a href="/contacts">Return to contact listing</a></p>